### ISSUE TITLE
re-using video_player in iOS

### ISSUE THREAD

**Issue by aytunch** [leonetosoft/flutter_video_player#1]
Hi,
I am having issues with the current video_player plugin. I am trying to display the videos recorded by the camera plugin. When I first display it, it is no problem. If I retake the video, more memory is leaked(not freed from OS). after 3-4 iterations, the app crashes. I test with an iPhone 7. When I use camera preset max the app crashes quicker.

[I saw you stating:](https://github.com/flutter/flutter/issues/24565#issuecomment-517888878)
```
Do not use:
_controller.dispose();
_controller.initialize();

//The app will crash very soon if you do this
```

So what should I do to display different VideoPlayer data sources from local files? What do you suggest? I would have used this repo however I need to solve this issue on iOS.

I am open to all suggestions.

Thanks.

**Comment by leonetosoft** [comment]
Come on, this problem is related to the fact that video_player does not accept changing the videoSource directly, without having to destroy / build the component.

If I had knowledge I would make this same PR work on IOS.
But I have 0% experience in IOS.

Why don't you create two widgets.

Widget 1: Lists the videos that will be played.
Widget 2: The screen of the video to be played.

When a user chooses to play video 1 you build WIDGET 2.
When he clicks on another video, you destroy widget 2 and create it again with
new assignments.

That way you won't have to change the VideoSource and you will build the video_player
whenever the user needs to watch a video, be it local or external

I believe it would work, but you need to make sure that you are destroying and building the component
